#!/usr/bin/env python3

import requests
import untangle
import sys
import os

outdir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "kits")
doc = untangle.parse(requests.get("http://hydrogen-music.org/feeds/drumkit_list.php").text)

def download(url, filename):
  with open(filename, "wb") as f:
    r = requests.get(url, stream=True)
    total_length = r.headers.get('content-length')
    if total_length is None: # no content length header
      f.write(r.content)
    else:
      dl = 0
      total_length = int(total_length)
      for data in r.iter_content(chunk_size=4096):
        dl += len(data)
        f.write(data)
        done = int(50 * dl / total_length)
        sys.stdout.write("\r[%s%s]" % ('=' * done, ' ' * (50-done)) )    
        sys.stdout.flush()


for kit in doc.drumkit_list.drumkit:
  name = kit.name.cdata
  url = kit.url.cdata
  filename = os.path.join(outdir, "%s.h2drumkit" % (name)).replace(' (sf)', '').replace(' (flac)', '').replace(' (Flac edition)', '')
  print("\nDownloading %s to %s" % (name, filename))
  download(url, filename)
