#!/usr/bin/env python3

import sys
import os
import time

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/lib")

from hydrogen import Hydrogen

def hydro2sfz(hydrofile, sfzfile):
  hydro = Hydrogen(hydrofile, os.path.dirname(sfzfile))
  
  sfz = """//+ Name: %s
//+ Date: %s
<global>loop_mode=one_shot
""" % (hydro.name, time.strftime("%Y-%m-%d"))

  for instrument in hydro.instruments:
    for layer in instrument["layers"]:
      sfz = sfz + "\n<region>key=%d lovel=%d hivel=%d sample=%s" % (instrument["region"] + 72, layer["min"] * 127, layer["max"] * 127, layer["file"])

  file = open(sfzfile,"w") 
  file.write(sfz)
  file.close()

if __name__ == "__main__":
  try:
    hydro2sfz(sys.argv[1], sys.argv[2])
  except:
    print("hydro2sfz <HYDROKIT_FILE> <SFZ_FILE>")
    print("\tConvert a hydrogen drumkit to a SFZ soundfont")