#!/usr/bin/env python3

import zipfile

def hydro2pti(filename_hydro, filename_pti):
  pass


if __name__ == "__main__":
  try:
    sys.argv[1]
    sys.argv[2]
  except Exception as e:
    print(e)
    print("hydro2renoise <HYDROKIT_FILE> <PTI_FILE>")
    print("\tConvert a hydrogen drumkit to a renoise instrument")
  
  hydro2pti(sys.argv[1], sys.argv[2])